#!/usr/bin/env python3
"""Offline contract tests for the single M20Pro field profile."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src/m20pro_navigation"))

from m20pro_navigation.field_profile_contract import (  # noqa: E402
    FieldProfileError,
    edge_environment,
    load_field_profile,
    render_edge_environment,
    validate_field_profile,
)


PROFILE_PATH = ROOT / "src/m20pro_bringup/config/m20pro_field_profile.yaml"


def raw_profile() -> dict:
    return yaml.safe_load(PROFILE_PATH.read_text(encoding="utf-8"))


def rejected(raw: dict) -> bool:
    try:
        validate_field_profile(raw)
    except FieldProfileError:
        return True
    return False


def main() -> None:
    profile = load_field_profile(PROFILE_PATH)
    assert profile["profile_hash"] == load_field_profile(PROFILE_PATH)["profile_hash"]
    assert len(profile["profile_hash"]) == 64
    assert profile["stair"]["obstacle_height_m"] == (
        profile["stair"]["max_step_height_m"]
        + profile["stair"]["obstacle_height_margin_m"]
    )

    typo = raw_profile()
    typo["stair"]["max_step_heigth_m"] = typo["stair"].pop("max_step_height_m")
    assert rejected(typo)

    string_integer = raw_profile()
    string_integer["stair_safety"]["required_clear_samples"] = "3"
    assert rejected(string_integer)

    impossible_corridor = raw_profile()
    impossible_corridor["stair"]["forward_min_m"] = 1.0
    impossible_corridor["stair"]["forward_max_m"] = 0.8
    assert rejected(impossible_corridor)

    stale_lease = raw_profile()
    stale_lease["stair_safety"]["stale_timeout_s"] = 2.0
    stale_lease["stair"]["mode_timeout_s"] = 1.5
    assert rejected(stale_lease)

    changed = deepcopy(raw_profile())
    changed["stair"]["max_step_height_m"] = 0.25
    changed_profile = validate_field_profile(changed)
    assert changed_profile["profile_hash"] != profile["profile_hash"]
    assert changed_profile["stair"]["obstacle_height_m"] == 0.27

    environment = edge_environment(profile)
    rendered = render_edge_environment(profile)
    assert environment["STAIR_OBSTACLE_HEIGHT"] == profile["stair"]["obstacle_height_m"]
    assert environment["FIELD_PROFILE_HASH"] == profile["profile_hash"]
    assert rendered.count("FIELD_PROFILE_HASH=") == 1
    assert "Do not edit this file" in rendered
    assert not (
        ROOT
        / "tools/edge_scan_feasibility/service/m20pro-edge-scan-106.env.edge_scan"
    ).exists()

    print("single field profile contract tests passed")


if __name__ == "__main__":
    main()
