#!/usr/bin/env python3
"""Offline contract tests for the single M20Pro field profile."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src/m20pro_navigation"))

from m20pro_navigation.field_profile_contract import (  # noqa: E402
    FieldProfileError,
    edge_environment,
    load_field_profile,
    render_edge_environment,
    validate_field_profile,
)


PROFILE_PATH = ROOT / "src/m20pro_bringup/config/m20pro_field_profile.yaml"


def raw_profile() -> dict:
    return yaml.safe_load(PROFILE_PATH.read_text(encoding="utf-8"))


def rejected(raw: dict) -> bool:
    try:
        validate_field_profile(raw)
    except FieldProfileError:
        return True
    return False


def leaf_count(value: object) -> int:
    if isinstance(value, dict):
        return sum(leaf_count(item) for item in value.values())
    return 1


def main() -> None:
    profile = load_field_profile(PROFILE_PATH)
    assert profile["profile_hash"] == load_field_profile(PROFILE_PATH)["profile_hash"]
    assert len(profile["profile_hash"]) == 64
    assert profile["stair"]["obstacle_height_m"] == (
        profile["stair"]["max_step_height_m"]
        + profile["stair"]["obstacle_height_margin_m"]
    )
    editable = {
        key: raw_profile()[key]
        for key in (
            "scan",
            "stair",
            "stair_safety",
            "stair_transition",
            "navigation",
            "localization",
        )
    }
    assert leaf_count(editable) == 67
    assert leaf_count(editable["navigation"]) == 28

    typo = raw_profile()
    typo["stair"]["max_step_heigth_m"] = typo["stair"].pop("max_step_height_m")
    assert rejected(typo)

    string_integer = raw_profile()
    string_integer["stair_safety"]["required_clear_samples"] = "3"
    assert rejected(string_integer)

    impossible_corridor = raw_profile()
    impossible_corridor["stair"]["forward_min_m"] = 1.0
    impossible_corridor["stair"]["forward_max_m"] = 0.8
    assert rejected(impossible_corridor)

    stale_lease = raw_profile()
    stale_lease["stair_safety"]["stale_timeout_s"] = 2.0
    stale_lease["stair"]["mode_timeout_s"] = 1.5
    assert rejected(stale_lease)

    unsafe_speed = raw_profile()
    unsafe_speed["navigation"]["controller"]["stopped_linear_speed_mps"] = 0.50
    assert rejected(unsafe_speed)

    impossible_costmap_rate = raw_profile()
    impossible_costmap_rate["navigation"]["costmap"]["local_publish_frequency_hz"] = 10.0
    impossible_costmap_rate["navigation"]["costmap"]["local_update_frequency_hz"] = 8.0
    assert rejected(impossible_costmap_rate)

    impossible_raytrace = raw_profile()
    impossible_raytrace["navigation"]["costmap"]["raytrace_range_m"] = 2.0
    impossible_raytrace["navigation"]["costmap"]["obstacle_range_m"] = 3.0
    assert rejected(impossible_raytrace)

    unsafe_localization = raw_profile()
    unsafe_localization["localization"]["pose_jump_candidate_radius_m"] = 0.8
    unsafe_localization["localization"]["pose_jump_reject_m"] = 0.6
    assert rejected(unsafe_localization)

    legacy_schema = raw_profile()
    legacy_schema["schema_version"] = 1
    assert rejected(legacy_schema)

    changed = deepcopy(raw_profile())
    changed["stair"]["max_step_height_m"] = 0.25
    changed_profile = validate_field_profile(changed)
    assert changed_profile["profile_hash"] != profile["profile_hash"]
    assert changed_profile["stair"]["obstacle_height_m"] == 0.27

    environment = edge_environment(profile)
    rendered = render_edge_environment(profile)
    assert environment["STAIR_OBSTACLE_HEIGHT"] == profile["stair"]["obstacle_height_m"]
    assert environment["FIELD_PROFILE_HASH"] == profile["profile_hash"]
    assert rendered.count("FIELD_PROFILE_HASH=") == 1
    assert "Do not edit this file" in rendered
    assert not (
        ROOT
        / "tools/edge_scan_feasibility/service/m20pro-edge-scan-106.env.edge_scan"
    ).exists()

    print("single field profile contract tests passed")


if __name__ == "__main__":
    main()
